# Generated by rust2rpm 10
# Tests are too much environment dependent
%bcond_with check
%global debug_package %{nil}

# We ship it as part of rust.src
%global __cargo_is_bin() false

%global crate cargo

Name:           rust-%{crate}
Version:        0.40.0
Release:        1%{?dist}
Summary:        Cargo, a package manager for Rust

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/cargo
Source:         %{crates_source}
# Initial patched metadata
# * No windows/macos
# * No rustc-workspace-hack
Patch0:         cargo-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging
%if %{with check}
BuildRequires:  git-core
%endif

%global _description %{expand:
Cargo, a package manager for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc ARCHITECTURE.md CONTRIBUTING.md README.md src/doc
%{cargo_registry}/%{crate}-%{version}/
%exclude %{cargo_registry}/%{crate}-%{version}/{appveyor.yml,etc}

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+deny-warnings-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+deny-warnings-devel %{_description}

This package contains library source intended for building other packages
which use "deny-warnings" feature of "%{crate}" crate.

%files       -n %{name}+deny-warnings-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+openssl-devel %{_description}

This package contains library source intended for building other packages
which use "openssl" feature of "%{crate}" crate.

%files       -n %{name}+openssl-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+pretty-env-logger-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pretty-env-logger-devel %{_description}

This package contains library source intended for building other packages
which use "pretty-env-logger" feature of "%{crate}" crate.

%files       -n %{name}+pretty-env-logger-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+pretty_env_logger-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pretty_env_logger-devel %{_description}

This package contains library source intended for building other packages
which use "pretty_env_logger" feature of "%{crate}" crate.

%files       -n %{name}+pretty_env_logger-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Dec 07 2019 Josh Stone <jistone@redhat.com> - 0.40.0-1
- Update to 0.40.0

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.36.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Fri Jun 07 2019 Josh Stone <jistone@redhat.com> - 0.36.0-1
- Update to 0.36.0

* Wed Apr 03 2019 Josh Stone <jistone@redhat.com> - 0.32.0-4
- Bump git2 and git2-curl dependencies

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.32.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Sat Dec 15 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.32.0-2
- Bump crossbeam-utils to 0.6

* Thu Dec 06 2018 Josh Stone <jistone@redhat.com> - 0.32.0-1
- Update to 0.32.0

* Sat Nov 17 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.31.0-1
- Update to 0.31.0

* Tue Nov 13 2018 Josh Stone <jistone@redhat.com> - 0.30.0-2
- Adapt to new packaging

* Mon Sep 10 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.29.0-2
- Switch to crossbeam-utils

* Sat Aug 04 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.29.0-1
- Update to 0.29.0

* Sun Jul 22 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.28.0-1
- Initial package
